from .build_number import BuildNumberCommand
from .clear_all import ClearAllCommand
from .clear_entry import ClearEntryCommand
from .backspace import BackspaceCommand
from .change_sign import ChangeSignCommand
from .build_fraction import SetBuilderTypeToFractionCommand
from .addition import AdditionCommand
from .subtaction import SubtractionCommand
from .multiplication import MultiplicationCommand
from .division import DivisionCommand
from .equality import EqualityCommand
